#!/usr/bin/env bash
#use a while loop to count up to 20 with a bunch of cases.
i=1
while [ $i -le 20 ];
do
	case $i in
		4) echo "4"
	   	   echo "bad luck from China"
   	        ;;
		9) echo "g"
	   	   echo "bad luck from Japan"
	        ;;
		17) echo "17"
	            echo "bad luck from Italy"
    	        ;;
		$i) echo "$i"
		;;
	esac
	i=$(( i + 1 ))
done	
