#!/usr/bin/env bash
#this script will display the time for 12 hours and 59 minutes.
i=1
while [ $i -le 60 ];
do
	i=$(( i+1 ))
	if [[ $i = 0 ]];
	then echo "Hour: 0";
	elif [[ i = 60 ]]; then
	echo "Hour: 1";
	else echo "$i";
	fi
done
