#!/usr/bin/env bash
#this script will display the time for 12 hours and 59 minutes.
i=1
h=0
while [ $h -le 12 ]
do
	echo "Hour: $h"
	while [ $i -le 59 ]
		do
		echo "$i"
		i=$(( i+1 ))
		done
	i=1
	h=$(( h+1 ))
done
