#!/usr/bin/env bash
#this script will display the time for 12 hours and 59 minutes.
i=0
h=0
while [ $i -le 1440; $h -le 12 ];
do
	i=$(( i+1 ))
	if [[ $i = 0 ]];
	then echo "Hour: 0";
	elif [[ i = 60 ]]; then
	echo "Hour: 1";
	elif [[ $i = 120 ]]; then
	echo "Hour: 2";
		elif [[ $i = 180 ]]; then
	echo  "Hour: 3";
		elif [[ $i = 240 ]]; then
	echo "Hour: 4";
		elif [[ $i = 300 ]]; then
	echo "Hour: 5";
	else echo "$i";
	fi
done
